/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter Variable', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        financial: {
          'primary': '#0161ef',
          'primary-content': '#ffffff',
          'secondary': '#0154cf',
          'secondary-content': '#ffffff',
          'accent': '#6d28d9',
          'accent-content': '#ffffff',
          'neutral': '#1f2937',
          'neutral-content': '#f3f4f6',
          'base-100': '#ffffff',
          'base-200': '#f9fafb',
          'base-300': '#f3f4f6',
          'base-content': '#1f2937',
          'info': '#3b82f6',
          'success': '#10b981',
          'warning': '#f59e0b',
          'error': '#ef4444',
        },
        'financial-dark': {
          'primary': '#0161ef',
          'primary-content': '#ffffff',
          'secondary': '#0154cf',
          'secondary-content': '#ffffff',
          'accent': '#6d28d9',
          'accent-content': '#ffffff',
          'neutral': '#f3f4f6',
          'neutral-content': '#1f2937',
          'base-100': '#030620',
          'base-200': '#0a0f2e',
          'base-300': '#111941',
          'base-content': '#e5ecf6',
          'info': '#3b82f6',
          'success': '#10b981',
          'warning': '#f59e0b',
          'error': '#ef4444',
        },
      },
      {
        relocation: {
          'primary': '#14b8a6',
          'primary-content': '#ffffff',
          'secondary': '#06b6d4',
          'secondary-content': '#ffffff',
          'accent': '#10b981',
          'accent-content': '#ffffff',
          'neutral': '#1f2937',
          'neutral-content': '#f3f4f6',
          'base-100': '#ffffff',
          'base-200': '#f9fafb',
          'base-300': '#f3f4f6',
          'base-content': '#1f2937',
          'info': '#3b82f6',
          'success': '#10b981',
          'warning': '#f59e0b',
          'error': '#ef4444',
        },
        'relocation-dark': {
          'primary': '#14b8a6',
          'primary-content': '#ffffff',
          'secondary': '#06b6d4',
          'secondary-content': '#ffffff',
          'accent': '#10b981',
          'accent-content': '#ffffff',
          'neutral': '#f3f4f6',
          'neutral-content': '#1f2937',
          'base-100': '#0f172a',
          'base-200': '#1e293b',
          'base-300': '#334155',
          'base-content': '#f1f5f9',
          'info': '#3b82f6',
          'success': '#10b981',
          'warning': '#f59e0b',
          'error': '#ef4444',
        },
      },
      {
        education: {
          'primary': '#8b5cf6',
          'primary-content': '#ffffff',
          'secondary': '#6366f1',
          'secondary-content': '#ffffff',
          'accent': '#f97316',
          'accent-content': '#ffffff',
          'neutral': '#1f2937',
          'neutral-content': '#f3f4f6',
          'base-100': '#ffffff',
          'base-200': '#f9fafb',
          'base-300': '#f3f4f6',
          'base-content': '#1f2937',
          'info': '#3b82f6',
          'success': '#10b981',
          'warning': '#f59e0b',
          'error': '#ef4444',
        },
        'education-dark': {
          'primary': '#8b5cf6',
          'primary-content': '#ffffff',
          'secondary': '#6366f1',
          'secondary-content': '#ffffff',
          'accent': '#f97316',
          'accent-content': '#ffffff',
          'neutral': '#f3f4f6',
          'neutral-content': '#1f2937',
          'base-100': '#18181b',
          'base-200': '#27272a',
          'base-300': '#3f3f46',
          'base-content': '#fafafa',
          'info': '#3b82f6',
          'success': '#10b981',
          'warning': '#f59e0b',
          'error': '#ef4444',
        },
      },
    ],
    darkTheme: 'financial-dark',
    base: true,
    styled: true,
    utils: true,
    logs: false,
  },
};
